export { default as AuditForm } from './AuditForm/AuditForm'
export { default as DetailsTable } from './DetailsTable/DetailsTable'
export { default as Summary } from './Summary/Summary'
export { default as AverageModules } from './AverageModules/AverageModules'
export { default as BPMGraph } from './BPMGraph/BPMGraph'
export { default as LUMGraph } from './LUMGraph/LUMGraph'
export { default as ETAGraph } from './ETAGraph/ETAGraph'
export { default as AverageTable } from './AverageTable/AverageTable'
export { default as ETATable } from './ETATable/ETATable'
export { default as KPITable } from './KPITable/KPITable'
export { default as KPIGraph} from './KPIGraph/KPIGraph'
export { default as DesviacionesTable } from './DesviacionesTable/DesviacionesTable'
export { default as PhotoAudit } from './PhotoAudit/PhotoAudit'
export { default as LoginForm } from './LoginForm/LoginForm'
export { default as IncidentSummary } from './InciddentSummary/IncidentSummary'